version: '3.4'
services:
  db:
    image: postgres:15
    env_file:
     - .env
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data/
    networks:
      - semper-ki-dev-network
  pgadmin:
    image: dpage/pgadmin4
    env_file:
     - .env
    ports:
      - "8088:80"
    volumes:
      - ./docker-pg-admin.json:/pgadmin4/servers.json
    networks:
      - semper-ki-dev-network
  files:
    image: redis:7
    env_file:
    - .env
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ./redis/data/:/var/lib/redis/data/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: --save 60 1 --loglevel warning --requirepass ${REDISPW}
    networks:
      - semper-ki-dev-network

networks:
  semper-ki-dev-network:

