version: '3'

services:
  backend-staging:
    image: backend-staging
    build:
      context: .
      dockerfile: ./Dockerfile.Server
    command: ["bash","run/run.sh","-e staging", "-m", "-c"]
    env_file:
     - .env.staging
    ports:
      - 127.0.0.1:8001:8000
    volumes:
      - .:/app
    networks:
      - semper-ki-staging-network

  db-staging:
    image: postgres:15
    env_file:
     - .env.staging
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data-dev/
    networks:
      - semper-ki-staging-network

  redis-staging:
    image: redis:7
    env_file:
      - .env.staging
    ports:
      - 127.0.0.1:6380:6379
    volumes:
      - ./redis/data/:/var/lib/redis/data/
      - ./docker/docker-service-redis-start.sh:/usr/local/bin/docker-service-redis-start.sh
    entrypoint: /usr/local/bin/docker-service-redis-start.sh # used to pass PW from environment variable change things there if needed
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - semper-ki-staging-network

  minio-staging:
    image: minio/minio
    container_name: minio-staging
    volumes:
      - ./minio/data:/data
      - ./docker/docker-service-minio-start.sh:/usr/local/bin/docker-service-minio-start.sh
    env_file:
      - .env.staging
    ports:
      - "127.0.0.1:4570:9000"
      - "127.0.0.1:9001:9001"
    entrypoint: /usr/local/bin/docker-service-minio-start.sh
    networks:
      - semper-ki-staging-network

  celery-worker:
    build:
      context: .
      dockerfile: ./MSQ/Dockerfile.MSQ.Server
    container_name: local-celery-worker-staging
    entrypoint: celery
    env_file:
      - .env.staging
    command: -A MSQ.module.celery worker -n local_worker --loglevel=info
    volumes:
      - .:/app
    networks:
      - semper-ki-staging-network

networks:
  semper-ki-staging-network: