version: '3.4'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:3000 manage.py runserver 0.0.0.0:8000"]
    ports:
      - 8000:8000
    volumes:
      - .:/app
