version: '3.4'
 
services:
  backend-staging:
    image: backend-staging
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["-e staging"]
    env_file:
     - .env.staging
    ports:
      - 127.0.0.1:8001:8000
    volumes:
      - .:/app
    networks:
      - semper-ki-staging-network

  db-staging:
    image: postgres:15
    env_file:
     - .env.staging
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data-dev/
    networks:
      - semper-ki-staging-network

  redis-staging:
    image: redis:7
    env_file:
      - .env.staging
    ports:
      - 127.0.0.1:6380:6379
    volumes:
      - ./redis/data/:/var/lib/redis/data/
      - ./docker/docker-service-redis-start.sh:/usr/local/bin/docker-service-redis-start.sh
    entrypoint: /usr/local/bin/docker-service-redis-start.sh # used to pass PW from environment variable change things there if needed
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - semper-ki-staging-network
  
  localstack-staging:
    image: localstack/localstack
    volumes:
      - ./localstack/:/var/lib/localstack
    env_file:
      - .env.staging
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_PERSISTENCE=1
    ports:
      - "127.0.0.1:4567:4566"
    networks:
      - semper-ki-staging-network

  celery-worker:
    build:
      context: .
      dockerfile: ./MSQ/Dockerfile.MSQ
    container_name: local-celery-worker
    entrypoint: celery
    env_file:
      - .env.staging
    command: -A MSQ.module.celery worker -n local_worker --loglevel=info
    volumes:
      - .:/app
    networks:
      - semper-ki-staging-network

networks:
  semper-ki-staging-network: