version: '3.4'
 
services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - backend_django/.env
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres:15
    env_file:
     - backend_django/.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data/