# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.11

EXPOSE 8000

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging when set to 1
ENV PYTHONUNBUFFERED=1

# Install psycopg2
RUN apt-get update \
    && apt-get -y install libpq-dev gcc bash iputils-ping curl gawk
# Install pip requirements
WORKDIR /app
COPY . /app
RUN python -m pip install -r requirements.txt


# RUN chmod +x app/*/*.sh

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
#CMD ["gunicorn", "--bind", "0.0.0.0:8000", "main.asgi", "--reload", "--capture-output", "--log-level", "debug", "--env", "DJANGO_SETTINGS_MODULE=main.settings.debug", "-k", "uvicorn.workers.UvicornWorker", "--workers",  "16", "--threads", "16", "--timeout", "12000"]