FROM python:3.11

# Set the working directory
WORKDIR /app

# Copy your Celery configuration and application code
COPY . /app

# Install dependencies
COPY requirements.txt /app/
RUN python3 -m pip install -r requirements.txt

RUN apt-get update \
    && apt-get -y install libpq-dev gcc bash iputils-ping curl gawk libgmp-dev git cmake


