# Generated by Django 4.1.3 on 2023-04-17 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCollection',
            fields=[
                ('orderCollectionID', models.CharField(max_length=513, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('createdWhen', models.DateTimeField(auto_now_add=True)),
                ('updatedWhen', models.DateTimeField()),
                ('accessedWhen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('subID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hashedID', models.CharField(max_length=513)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('address', models.JSONField()),
                ('createdWhen', models.DateTimeField(auto_now_add=True)),
                ('updatedWhen', models.DateTimeField()),
                ('accessedWhen', models.DateTimeField(auto_now=True)),
                ('orders', models.ManyToManyField(to='backend_django.ordercollection')),
            ],
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('subID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hashedID', models.CharField(max_length=513)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.JSONField()),
                ('createdWhen', models.DateTimeField(auto_now_add=True)),
                ('updatedWhen', models.DateTimeField()),
                ('accessedWhen', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(to='backend_django.user')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderID', models.CharField(max_length=513, primary_key=True, serialize=False)),
                ('userOrders', models.JSONField()),
                ('status', models.CharField(max_length=100)),
                ('userCommunication', models.JSONField()),
                ('files', models.JSONField()),
                ('dates', models.JSONField()),
                ('createdWhen', models.DateTimeField(auto_now_add=True)),
                ('updatedWhen', models.DateTimeField()),
                ('accessedWhen', models.DateTimeField(auto_now=True)),
                ('orderCollectionKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='backend_django.ordercollection')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('subID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hashedID', models.CharField(max_length=513)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.JSONField()),
                ('uri', models.CharField(max_length=200)),
                ('createdWhen', models.DateTimeField(auto_now_add=True)),
                ('updatedWhen', models.DateTimeField()),
                ('accessedWhen', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(to='backend_django.user')),
            ],
        ),
    ]
