# Generated by Django 4.1.3 on 2023-08-02 14:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCollection',
            fields=[
                ('orderCollectionID', models.CharField(max_length=513, primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('createdWhen', models.DateTimeField(auto_now_add=True)),
                ('updatedWhen', models.DateTimeField()),
                ('accessedWhen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderID', models.CharField(max_length=513, primary_key=True, serialize=False)),
                ('userOrders', models.JSONField()),
                ('status', models.IntegerField()),
                ('userCommunication', models.JSONField()),
                ('files', models.JSONField()),
                ('dates', models.JSONField()),
                ('client', models.CharField(max_length=513)),
                ('contractor', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=513), size=None)),
                ('createdWhen', models.DateTimeField(auto_now_add=True)),
                ('updatedWhen', models.DateTimeField()),
                ('accessedWhen', models.DateTimeField(auto_now=True)),
                ('orderCollectionKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='backend_django.ordercollection')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('subID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hashedID', models.CharField(max_length=513)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('organizations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=513), size=None)),
                ('details', models.JSONField()),
                ('createdWhen', models.DateTimeField(auto_now_add=True)),
                ('updatedWhen', models.DateTimeField()),
                ('accessedWhen', models.DateTimeField(auto_now=True)),
                ('lastSeen', models.DateTimeField()),
                ('orders', models.ManyToManyField(to='backend_django.ordercollection')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('subID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hashedID', models.CharField(max_length=513)),
                ('name', models.CharField(max_length=100)),
                ('details', models.JSONField()),
                ('canManufacture', models.BooleanField(default=False)),
                ('uri', models.CharField(max_length=200)),
                ('createdWhen', models.DateTimeField(auto_now_add=True)),
                ('updatedWhen', models.DateTimeField()),
                ('accessedWhen', models.DateTimeField(auto_now=True)),
                ('ordersReceived', models.ManyToManyField(to='backend_django.orders')),
                ('ordersSubmitted', models.ManyToManyField(to='backend_django.ordercollection')),
                ('users', models.ManyToManyField(to='backend_django.user')),
            ],
        ),
    ]
