# Generated by Django 4.1.3 on 2023-04-03 15:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('uID', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('orderIDs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
                ('userOrders', models.JSONField()),
                ('orderStatus', models.JSONField()),
                ('userCommunication', models.JSONField()),
                ('files', models.JSONField()),
                ('createdWhen', models.DateTimeField(auto_now_add=True)),
                ('updatedWhen', models.DateTimeField()),
                ('accessedWhen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
