# Generated by Django 4.1.3 on 2023-08-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='details',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
