# Generated by Django 4.1.3 on 2023-04-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_django', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='dates',
            field=models.JSONField(default='<function now at 0x7fa6dc2e0670>'),
            preserve_default=False,
        ),
    ]
