# Generated by Django 4.1.3 on 2023-08-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_django', '0002_orders_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercollection',
            name='client',
            field=models.CharField(default='', max_length=513),
            preserve_default=False,
        ),
    ]
