# Generated by Django 4.1.3 on 2023-09-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_django', '0003_ordercollection_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercollection',
            name='details',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
