# Generated by Django 4.2.7 on 2023-11-23 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('code_General', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectID', models.CharField(max_length=513, primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('client', models.CharField(max_length=513)),
                ('details', models.JSONField()),
                ('createdWhen', models.DateTimeField(auto_now_add=True)),
                ('updatedWhen', models.DateTimeField()),
                ('accessedWhen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('processID', models.CharField(max_length=513, primary_key=True, serialize=False)),
                ('processDetails', models.JSONField()),
                ('processStatus', models.IntegerField()),
                ('serviceDetails', models.JSONField()),
                ('serviceStatus', models.IntegerField()),
                ('serviceType', models.IntegerField()),
                ('client', models.CharField(max_length=513)),
                ('createdWhen', models.DateTimeField(auto_now_add=True)),
                ('updatedWhen', models.DateTimeField()),
                ('accessedWhen', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asContractor', to='code_General.organization')),
                ('dependenciesIn', models.ManyToManyField(related_name='processesIn', to='code_SemperKI.process')),
                ('dependenciesOut', models.ManyToManyField(related_name='processesOut', to='code_SemperKI.process')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='code_SemperKI.project')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('dataID', models.CharField(max_length=513, primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('data', models.JSONField()),
                ('details', models.JSONField()),
                ('createdBy', models.CharField(max_length=513)),
                ('contentID', models.CharField(max_length=513)),
                ('createdWhen', models.DateTimeField(auto_now_add=True)),
                ('updatedWhen', models.DateTimeField()),
                ('accessedWhen', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='code_SemperKI.process')),
            ],
            options={
                'ordering': ['createdWhen'],
            },
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['processID'], name='processIDs_idx'),
        ),
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['process'], name='process_idx'),
        ),
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['process', 'type'], name='process_dataType_idx'),
        ),
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['process', 'contentID'], name='process_dataID_idx'),
        ),
    ]
