# Generated by Django 4.2.7 on 2024-08-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_SemperKI', '0002_rename_details_project_projectdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('nodeID', models.CharField(max_length=513, primary_key=True, serialize=False)),
                ('nodeName', models.CharField(max_length=513)),
                ('nodeType', models.CharField(max_length=513)),
                ('context', models.CharField(max_length=10000)),
                ('properties', models.JSONField()),
                ('createdWhen', models.DateTimeField(auto_now_add=True)),
                ('updatedWhen', models.DateTimeField()),
                ('accessedWhen', models.DateTimeField(auto_now=True)),
                ('edges', models.ManyToManyField(to='code_SemperKI.node')),
            ],
            options={
                'indexes': [models.Index(fields=['nodeID'], name='nodeID_idx'), models.Index(fields=['nodeType'], name='node_type_idx'), models.Index(fields=['properties'], name='node_properties_idx')],
            },
        ),
    ]
