# Generated by Django 4.2.7 on 2024-08-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_SemperKI', '0003_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='createdBy',
            field=models.CharField(default='', max_length=513),
            preserve_default=False,
        ),
    ]
