# Generated by Django 4.2.7 on 2024-08-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_SemperKI', '0004_node_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
