# Generated by Django 4.2.7 on 2024-09-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_SemperKI', '0005_node_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='clonedFrom',
            field=models.CharField(default='', max_length=513),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='uniqueID',
            field=models.CharField(default='', max_length=513),
            preserve_default=False,
        ),
    ]
