# Generated by Django 4.2.7 on 2024-10-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_SemperKI', '0006_node_clonedfrom_node_uniqueid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.CharField(max_length=513, primary_key=True, serialize=False)),
                ('userHashedID', models.CharField(max_length=513)),
                ('event', models.JSONField()),
                ('createdWhen', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['createdWhen'],
                'indexes': [models.Index(fields=['userHashedID'], name='event_user_idx')],
            },
        ),
    ]
