# Generated by Django 4.2.7 on 2024-10-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_SemperKI', '0007_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
